"use strict";
let myName = document.getElementById("name");
let desig = document.getElementById("desig");
let phone = document.getElementById("phone");
let email = document.getElementById("email");
let add = document.getElementById("add");
let pass = document.getElementById("pass");
let deg = document.getElementById("deg");
let uni = document.getElementById("uni");
let pass1 = document.getElementById("pass1");
let deg1 = document.getElementById("deg1");
let uni1 = document.getElementById("uni1");
let pass2 = document.getElementById("pass2");
let deg2 = document.getElementById("deg2");
let uni2 = document.getElementById("uni2");
let skill1 = document.getElementById("skill1");
let skill2 = document.getElementById("skill2");
let skill3 = document.getElementById("skill3");
let skill4 = document.getElementById("skill4");
let skill5 = document.getElementById("skill5");
let lang1 = document.getElementById("lang1");
let lang2 = document.getElementById("lang2");
let language3 = document.getElementById("language3");
let job = document.getElementById("job");
let styear = document.getElementById("styear");
let endyear = document.getElementById("endyear");
let company = document.getElementById("company");
let locat = document.getElementById("locat");
let ach1 = document.getElementById("ach1");
let ach2 = document.getElementById("ach2");
let ach3 = document.getElementById("ach3");
let job1 = document.getElementById("job1");
let styear1 = document.getElementById("styear1");
let endyear1 = document.getElementById("endyear1");
let company1 = document.getElementById("company1");
let locat1 = document.getElementById("locat1");
let ach4 = document.getElementById("ach4");
let ach5 = document.getElementById("ach5");
let ach6 = document.getElementById("ach6");
let job3 = document.getElementById("job3");
let styear3 = document.getElementById("styear3");
let endyear3 = document.getElementById("endyear3");
let company3 = document.getElementById("company3");
let locat3 = document.getElementById("locat3");
let ach7 = document.getElementById("ach7");
let ach8 = document.getElementById("ach8");
let ach9 = document.getElementById("ach9");
let pic = document.getElementById("pic");
let submitBtn = document.getElementById('submitBtn');
let form = document.getElementById('form');
form?.addEventListener("submit", (event) => {
    event.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("pass", pass.value);
    localStorage.setItem("deg", deg.value);
    localStorage.setItem("uni", uni.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("uni1", uni1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("skill5", skill5.value);
    localStorage.setItem("lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("language3", language3.value);
    localStorage.setItem("job", job.value);
    localStorage.setItem("styear", styear.value);
    localStorage.setItem("endyear", endyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("locat", locat.value);
    localStorage.setItem("ach1", ach1.value);
    localStorage.setItem("ach2", ach2.value);
    localStorage.setItem("ach3", ach3.value);
    localStorage.setItem("job1", job1.value);
    localStorage.setItem("styear1", styear1.value);
    localStorage.setItem("endyear1", endyear1.value);
    localStorage.setItem("company1", company1.value);
    localStorage.setItem("locat1", locat1.value);
    localStorage.setItem("ach4", ach4.value);
    localStorage.setItem("ach5", ach5.value);
    localStorage.setItem("ach6", ach6.value);
    localStorage.setItem("job3", job3.value);
    localStorage.setItem("styear3", styear3.value);
    localStorage.setItem("endyear3", endyear3.value);
    localStorage.setItem("company3", company3.value);
    localStorage.setItem("locat3", locat3.value);
    localStorage.setItem("ach7", ach7.value);
    localStorage.setItem("ach8", ach8.value);
    localStorage.setItem("ach9", ach9.value);
    window.location.href = "./resume/resume.html";
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
});
